## General
text = "#cdd6f4"

bg0 = "11111b"
bg1 = "#1e1e2e"
bg2 = "#313244"

accent1 = "#cba6f7" # Mauve
accent2 = "#fab387" # Peach

[terminal]
fg = "#cba6f7"
bg = "#1e1e2e"

black = "#11111b"
blue = "#89b4fa"
cyan = "#fab387"
green = "#74c7ec"
magenta = "#cba6f7"
red = "#f38ba8"
white = "#cdd7f4"
yellow = "#f2cdcd"

## App specific
hyprland_border = "#11111b"

[notification_border]
normal = "#89b4fa"  # Blue
urgent = "#f38ba8"  # Red

[waybar]
text = "#cdd6f4"    # Global text
bg1 = "#1e1e2e"     # Global bg1
bg2 = "#313244"     # Global bg2
border = "#cba6f7"  # Mauve

